#!/bin/bash

#SBATCH -J mmseqs
#SBATCH --nodes=1 --cpus-per-task=24 
#SBATCH --error=test1.stderr
#SBATCH --output=time_output97.txt
#SBATCH --chdir=/coe_data/spprl/student/fasino/mmseqs2/SILVA/fulltiming

echo $SLURM_JOB_ID 
module load python/3.11.5 

start_time=$(date +"%s")

/coe_data/spprl/student/fasino/mmseqs2/mmseqs/bin/mmseqs cluster ../silvafulldb fulltimingclu0.97 tmp --cluster-mode 0 --min-seq-id 0.97 

end_time=$(date +"%s")

elapsed_time=$((end_time - start_time))

echo "Script execution time: $elapsed_time seconds" >> fulltime_output97.txt
